evbg:
  target: development_pass
  outputs:
    local:
      type: duckdb
      path: evbg.duckdb
    development:
      account: vha23173
      authenticator: externalbrowser
      database: RISK_EVENTS
      role: ACCOUNTADMIN
      schema: ANALYTICS
      threads: 1
      type: snowflake
      user: suriel.garcia@everbridge.com
      warehouse: DEV_WH
    development_pass:
      account: vha23173
      user: "{{ env_var('DBT_USER', 'atlantis_user') }}"
      password: "{{ env_var('DBT_PASSWORD', var('dbt_password')) }}"
      database: RISK_EVENTS
      role: ACCOUNTADMIN
      schema: ANALYTICS
      threads: 1
      type: snowflake
      user: suriel.garcia@everbridge.com
      warehouse: DEV_WH
    production:
      account: vha23173
      authenticator: externalbrowser
      database: RISK_EVENTS
      role: ACCOUNTADMIN
      schema: ANALYTICS
      threads: 1
      type: snowflake
      user: suriel.garcia@everbridge.com
      warehouse: DEV_WH

