version: 2

models:

  - name: stg_alerts
    description: This model cleans up customer data
    columns:
      - name: ALERTID
      - name: ORGANIZATIONID
      - name: EXPIREAT
      - name: EXPIRYDATE
      - name: IMPACTAREA
      - name: ISACTIVE
      - name: REVISION
      - name: SNOOZEUNTIL
      - name: RISKEVENTID
      - name: RISKEVENTEXTERNALID
      - name: RISKEVENTCONFIGURATIONID
      - name: DWINSERTEDDATE
      - name: RESUMETOKEN
      - name: PAYLOAD
      - name: RISK_EVENT_SOURCE
      - name: RISK_EVENT_JOIN_ID
      - name: ALERT_SOURCE


  - name: stg_alerts_action_history
    description: This model cleans up order data
    columns:
      - name: ALERTID
      - name: ORGANIZATIONID
      - name: REVISION
      - name: ACTIONTYPE
      - name: ACTIONTIME
      - name: PREVIOUSVERSION
      - name: DISPOSITION
      - name: NOTES
      - name: USERNAME
      - name: RESUMETOKEN
      - name: ACTIONPAYLOAD
      - name: ALERT_SOURCE 

